### ISSUE TITLE
HDF5 License violation

### ISSUE THREAD

**Issue by isuruf** [conda-forge/itk-feedstock#11]
Note that HDF5 license requires the copyright text be distributed.
Other dependencies might need their licenses to be distributed as well.

**Comment by isuruf** [comment]
@conda-forge/core, the maintainers here have not responded. I suggest pulling this package from conda-forge.

**Comment by CJ-Wright** [comment]
@conda-forge/itk

**Comment by CJ-Wright** [comment]
Activity pinging the maintainers might be a better way to get a response, since not all the maintainers may be watchers and therefore will miss the issue completely and the ping may bring more attention than just an issue more generally.

**Comment by jakirkham** [comment]
It’s also not clear (at least to me) what the complaint is. Could you please explain a bit more about the problem?

**Comment by isuruf** [comment]
This package is vendoring HDF5, but is not distributing their license.

**Comment by jakirkham** [comment]
Is it vendoring or statically linking?

**Comment by thewtex** [comment]
@isuruf thanks for the note. The copyright is added to the *NOTICE* file in https://github.com/InsightSoftwareConsortium/ITK/pull/1333. This file is distributed in the binary package and also contains the copyright for other third party libraries.

**Comment by ocefpaf** [comment]
While it would be nice to list that file in the license this is solved b/c the license is in the final package.

**Comment by isuruf** [comment]
Until there is a new version, this issue is not closed.
