### ISSUE TITLE
Shared Libraries Missing?

### ISSUE THREAD

**Issue by rlizzo** [conda-forge/itk-feedstock#2]
Hello all! I wasn't sure whether to post this as a PR or as an issue.

ITK is a dependency of [a project](https://github.com/vmtk/vmtk) I maintain, and we are trying to make the switch to distributing it on conda-forge. Unfortunately, there seem to bee some incompatibilities with the package in it's current state as we rely on the C++ shared libraries rather than the python bindings. 

The two big issues that I am having right now are:
- Most of the standard libITKfoo.so / dyld binaries are missing from the lib folder. 
- The ITKReview module is not included within the package taken from PyPi.

I'm wondering if there is any interest in making the ITK feedstock compatible with general code projects? **We have the conda-build scripts already written to generate a standard build:** https://github.com/vmtk/conda-recipes/tree/master/itk. Only the option to include python bindings is missing right now.

I wanted to reach out and get your input before going ahead and submitting a PR. I'd really appreciate any feedback you might have: is this something of interest, or if there are any techincal reasons that this has not been implemented yet? 

Thank you!

**Comment by rlizzo** [comment]
ping recipe maintainers: @thewtex and @ericdill

**Comment by isuruf** [comment]
Shared libraries are in `libitk-feedstock`

**Comment by thewtex** [comment]
@rlizzo as @isuruf suggested, please build against the `libitk` conda-forge package.
